baseURL = "www.luxiangze.xyz"
title = "鹿芗泽"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "鹿芗泽"
    # logo = "//blog.ertuil.top/avater.jpg"
    bio = """
    <p>人生，总会有不期而遇的温暖和生生不息的希望。 </p>
    <br />
    <p>In life, there will always be unexpected warmth and endless hope.</p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "gyongkang.outlook.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/luxiangze/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/username/"
    name = "instagram"
    weight = 1
